"use client";

import Header from "@/layout/header/Header";
import "./globals.scss";
import { Inter } from "next/font/google";
import { Providers } from "@/store/provider";
import { AuthContextProvider } from "@/firebase/AuthContext";
import { AnimatePresence } from "framer-motion";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        ></meta>
      </Head>
      <body className={inter.className}>
        <Providers>
          <AuthContextProvider>
            <AnimatePresence mode="wait">
              <div className="layout-container">
                <div className="body-content">
                  <Header />
                  {children}
                </div>
              </div>
            </AnimatePresence>
          </AuthContextProvider>
        </Providers>
      </body>
    </html>
  );
}
